plugins {
    id 'com.android.application'
}

android {
    namespace 'com.homeflow.test'
    compileSdk 35

    defaultConfig {
        applicationId 'com.homeflow.stable'
        minSdk 26
        targetSdk 35
        versionCode 9
        versionName '0.9-stable-fresh'
    }

    buildTypes {
        debug { minifyEnabled false }
        release { minifyEnabled false }
    }
}
