plugins {
    id 'com.android.application'
}

android {
    namespace 'com.homeflow.test'
    compileSdk 35

    defaultConfig {
        applicationId 'com.homeflow.test'
        minSdk 26
        targetSdk 35
        versionCode 5
        versionName '0.5-stable'
    }

    buildTypes {
        debug { minifyEnabled false }
        release { minifyEnabled false }
    }
}
